name: Build OrangeFox for Garnet

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox Branch (ex: 12.1)'
        required: true
        default: '12.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup build environment
      run: |
        sudo apt update && sudo apt -y upgrade
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
        sudo apt install -y bash

    - name: Sync OrangeFox sources
      run: |
        mkdir -p OFX
        cd OFX
        git clone https://gitlab.com/OrangeFox/sync.git
        cd sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ..
    
    - name: Add your Garnet device tree
      run: |
        cd OFX
        mkdir -p fox_${{ github.event.inputs.MANIFEST_BRANCH }}/device/xiaomi/garnet
        git clone https://github.com/cocka11/recovery_garnet.git fox_${{ github.event.inputs.MANIFEST_BRANCH }}/device/xiaomi/garnet

    - name: Build OrangeFox
      run: |
        cd OFX/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_garnet-eng
        make clean
        mka recoveryimage
