name: Build OrangeFox - garnet

on:
  workflow_dispatch: # Lejon nisjen manuale të build-it

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rritja e hapësirës në Disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Instalimi i Varësive (Dependencies)
        run: |
          sudo apt update
          sudo apt install -y bc build-essential python3-setuptools x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip gperf bison clang cmake git-core gnupg flex curl lzop libncurses5-dev libsdl1.2-dev libssl-dev libxml2 python2-minimal rsync schedtool squashfs-tools wget zip zlib1g-dev

      - name: Konfigurimi i Repo
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sinkronizimi i Burimit (Source)
        run: |
          mkdir ~/fox && cd ~/fox
          repo init --depth=1 -u https://gitlab.com/OrangeFox/Manifest.git -b fox_12.1
          repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Clonimi i Device Tree
        run: |
          cd ~/fox
          git clone https://gitlab.com/OrangeFox/device/garnet.git device/xiaomi/garnet

      - name: Ndërtimi (Build) i OrangeFox
        run: |
          cd ~/fox
          set -e
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_REPLACE_TOOLBOX=1
          export LC_ALL="C"
          lunch twrp_garnet-eng
          mka adbd recoveryimage -j$(nproc --all)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-Garnet
          path: ~/fox/out/target/product/garnet/OrangeFox-*.zip
          
